name: 3-tier-node-js-app

on:
  push:
    branches:
      - feature/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
env:
  AWS_REGION: "us-east-1"

jobs:
  buil-Dockerd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3i
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}
