name: 3-tiers-node-js-app

on:
  #trigger/start job when push happens to any of specified branches
  push:
    branches:
      - feature/**
      - staging

# required permissions by GitHub Actions for assuming AWS IAM role
permissions: 
    id-token: write
    contents: read
env:
    AWS_REGION: "us-east-1"

jobs:
  build-applicacion:
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staigin') && 'staging' || 'dev'}}
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v3

    # login to aws account 
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.IAM_ROLE }}
        role-session-name: GitHubActionsRoleSession
        aws-region: ${{ env.AWS_REGION}}


    # login to ect
    - id: login-ecr
      name: login into amazon ecr 
      uses: aws-actions/amazon-ecr-loging@v2

    # Build tag and push docker images
    - name: Build tag and push docker images
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: api
        IMAGE_TAG: "0.1" #{{ github.sha}}
      working-directory: ./api
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    
  
